# Generated by Django 3.1.6 on 2021-04-03 20:29

import AllModels.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subAuthor', models.CharField(default='Fuji', max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('images', models.ImageField(blank=True, null=True, upload_to=AllModels.models.Post.upload_location, verbose_name='Image')),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='Published')),
                ('Published', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=250)),
                ('category', models.CharField(choices=[('News', 'News'), ('Politics', 'Politics'), ('Education', 'Education'), ('Blog', 'Blog'), ('Article', 'Article'), ('Entertainment', 'Entertainment')], default='News', max_length=50)),
                ('campus', models.CharField(choices=[('University', 'University'), ('HTU', 'HTU'), ('Legon', 'Legon'), ('KNUST', 'KNUST'), ('UCC', 'UCC'), ('UHAS', 'UHAS'), ('KTU', 'KTU')], default='University', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Published',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AllModels.post')),
            ],
        ),
    ]
