# Generated by Django 3.1.6 on 2021-04-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllModels', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='null'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='null', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True, default='null'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, default='null', max_length=250),
        ),
    ]
